name: Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Run Docker container to compile assets
      uses: addnab/docker-run-action@v3
      with:
        image: omni-webserver:latest
        options: -v ./www:/var/www
        run: |
          composer install
          npm install
          npm run build
