name: Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Run Composer & npm
      run: |
        sudo docker exec omni-webserver composer install
        sudo docker exec omni-webserver npm install
        sudo docker exec omni-webserver npm run build
