name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: omni-webserver:latest
    steps:
      - name: Pull
        run: |
          ls
          git pull
